abstract final class AppRoutes {
  static const splash = '/';
  static const login = '/login';
  static const register = '/register';
  static const profileSetup = '/profile-setup';
  static const profile = '/profile';
  static const dashboard = '/dashboard';
  static const goalSettings = '/dashboard/goal-settings';
  static const dashboardAnalyticsDetails = '/dashboard/analytics-details';
  static const chat = '/social/chat';
  static const leaderboard = '/social/leaderboard';
  static const workoutList = '/workouts';
  static const startWorkout = '/workouts/start';
  static const activeWorkout = '/workouts/active';
  static const workoutResult = '/workouts/result';
  static const foodDiary = '/nutrition/diary';
  static const addFood = '/nutrition/add';
  static const productDetails = '/nutrition/product-details';
  static const stepCounter = '/steps';
}
